# .github/workflows/auto-merge-pr.yml

name: Auto Merge PRs With Valid TXT Files

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  check-and-merge:
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout pull request code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Check if only new TXT files in 'requests/' were added
        id: filecheck
        run: |
          base_sha=${{ github.event.pull_request.base.sha }}
          head_sha=${{ github.event.pull_request.head.sha }}
          echo "Comparing $base_sha to $head_sha"

          changed_files=$(git diff --name-status $base_sha $head_sha)
          echo "$changed_files" > changed_files.txt

          valid=true
          while IFS=$'\t' read -r status file; do
            if [[ "$status" != A* || ! "$file" =~ ^requests/.*\.txt$ ]]; then
              valid=false
              break
            fi
          done < changed_files.txt

          echo "valid=$valid" >> $GITHUB_OUTPUT

      - name: Debug PR number
        run: echo "PR number: ${{ github.event.pull_request.number }}"

      - name: Auto-merge PR if valid
        if: steps.filecheck.outputs.valid == 'true'
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
